[mypy]
python_version = 3.13
warn_unused_configs = True
check_untyped_defs = True
mypy_path = src

[mypy-google_auth_oauthlib.*]
ignore_missing_imports = True

[mypy-googleapiclient.*]
ignore_missing_imports = True